openapi: 3.0.3
info:
  title: loginSystem api
  description: a loginSignup system
  version: 1.0.11
servers:
  - url: http://localhost:3000
tags:
  - name: signup
    description: a signup link
paths:
  /signup:
    post:
      tags:
        - logs
      description: user input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login-system'
        required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  username: username
                  email: email
                  phone: phone
        400:
          description: error
          content:
            application/json:
              schema:
                type: object
                example:
                  message: user already exists
                  message1: please enter username
                  message2: please enter email or phone number
                  message3: please enter password
  /login:
    post:
      tags:
        - logins
      description: user login
      requestBody:
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/loginUser'
        required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                 accessToken: accessToken
        400:
          description: error
          content:
            application/json:
              schema:
                type: object
                example:
                  message: password incorrect
                  message1: please enter username or email or phone number
                  message2: please enter password
  /profile:
    get:
      tags:
        - profile page
      description: user profile page
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  profile: profile
        400:
          description: error
          content:
            application/json:
              schema:
                type: object
                example:
                  error: user not authenticated
components:
  schemas:
    login-system:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          description: username
          example: jack
        email:
          type: string
          description: email
          example: jack@gmail.com
        phone:
          type: integer
          format: int64
          example: 8217643875
        password:
          type: string
          description: user password
          example: abc123
    loginUser:
      type: object
      properties:
        username:
          type: string
          description: username
          example: pop
        email:
          type: string
          description: email
          example: pop@gmail.com
        password:
          type: string
          description: password
          example: abc
                  